---
- name: Install base packages
  sudo: yes
  apt:
    name: "{{ item }}"
  with_items:
    - ack-grep
    - ansible
    - apt-listchanges
    - apt-xapian-index
    - aptitude
    - ascii
    - bash-completion
    - bridge-utils
    - bzr
    - colordiff
    - cron
    - curl
    - debian-goodies
    - debianutils
    - debootstrap
    - dmidecode
    - dnsutils
    - dstat
    - e2fsprogs
    - eatmydata
    - ethtool
    - finger
    - git
    - git-extras
    - git-remote-bzr
    - gnupg2
    - gnutls-bin
    - htop
    - iftop
    - iotop
    - iperf
    - iptables
    - iputils-ping
    - ipv6calc
    - ipython
    - jq
    - lftp
    - logrotate
    - lsof
    - lvm2
    - man-db
    - manpages
    - mc
    - mdns-scan
    - moreutils
    - mosh
    - mtr-tiny
    - mutt
    - netcat-traditional
    - nmap
    - pcscd
    - pwgen
    - pxz
    - qrencode
    - reptyr
    - rsync
    - rsyslog
    - scdaemon
    - screen
    - smartmontools
    - socat
    - strace
    - sudo
    - swaks
    - tcpdump
    - tcptraceroute
    - telnet
    - time
    - traceroute
    - tsocks
    - units
    - vim-nox
    - vnstat
    - wget
    - xz-utils
    - zsync
